(lecture03:homework)=
# Homework 3

+ Type your name and email in the "Student details" section below.
+ Develop the code and generate the figures you need to solve the problems using this notebook.
+ For the answers that require a mathematical proof or derivation you can either:
    
    - Type the answer using the built-in latex capabilities. In this case, simply export the notebook as a pdf and upload it on gradescope; or
    - You can print the notebook (after you are done with all the code), write your answers by hand, scan, turn your response to a single pdf, and upload on gradescope.

+ The total homework points are 100. Please note that the problems are not weighed equally.

```{note}
+ This is due before the beginning of the next lecture.
+ Please match all the pages corresponding to each of the questions when you submit on gradescope.
```

## Student details

+ **First Name:**
+ **Last Name:**
+ **Email:**

(lecture03:homework:problem1)=
## Problem 1 - High-performance buildings

In this problem we are going to use the `pandas` library to analyze a real dataset collected as part of the NSF-funded project [Sociotechnical Systems to Enable Energy-Aware Residential Communities](https://www.energyawarecommunities.org/).
You can find the raw dataset here:

https://github.com/PurdueMechanicalEngineering/me-297-intro-to-data-science/raw/master/data/temperature_raw.xlsx

Feel free to download it and open it up in Excel.

### Uploading data files to Google Colab

The first thing we are going to do in this problem is make this file accessible from this notebook. We could simply use the ``download()`` function that I introduced in the lecture. I will put the code at the very last block for your convenience.
However, I still want to show you how you can upload your own data. Here we go.

Go to your Google Drive. We need to select a folder to put the files. To keep things simple, let's just dump everything in "My Drive/Colab Notebooks," i.e., the same folder that contains the copy of this Jupyter notebook which you should have already made  Once you have entered this folder in your Google Drive (just double click on it), drag and drop the `temperature_raw.xlsx` file in there.

Now we need to make the Google Drive visible from this computational session. We do this by mounting the drive. You need to run this code and follow the instructions:

In [ ]:
# The following code does not run unless you are running the notebook on Google Colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Finally, change directories so that the data files are in the current working directory:

In [ ]:
# Only if you are running on Google Colab...
# Print working directory before changing
!pwd
# Change to the desired directory on Google drive
%cd "/content/drive/My Drive/Colab Notebooks"
# Print working directory after changing
!pwd
# List the contents of the directory - Make sure it does contain the files we want:
!ls

/content/drive/My Drive/Colab Notebooks
/content/drive/My Drive/Colab Notebooks
/content/drive/My Drive/Colab Notebooks
'Copy of homework_01.ipynb'  'Copy of homework_02.ipynb'   temperature_raw.xlsx


Now you should have access to the file and you can **skip the next code block.**
If you tried and something went wrong, simply run the code block below and it will put the data file in the right location for you.

In [ ]:
# Only run this if the steps above failed for some reason.
import requests
import os
def download(url, local_filename=None):
    """
    Downloads the file in the ``url`` and saves it in the current working directory.
    """
    data = requests.get(url)
    if local_filename is None:
        local_filename = os.path.basename(url)
    with open(local_filename, 'wb') as fd:
        fd.write(data.content)
   
# The url of the file we want to download
url = 'https://github.com/PurdueMechanicalEngineering/me-297-intro-to-data-science/raw/master/data/temperature_raw.xlsx'
download(url)

### Loading Excel files

Use the ``pd.read_excel`` function to read the `temperature_raw.xlsx` file.
Name the data frame you read `df`.

In [ ]:
import pandas as pd
df = pd.read_excel('temperature_raw.xlsx')

### Questions

Now that you have access to the data frame, let's explore it.
Answer the following questions.

+ Print the first 10 rows of the data frame `df`:

In [ ]:
df.head(10)

household        date  score     t_out     t_unit        hvac
0        a1  2018-01-07  100.0  4.283373  66.693229  246.473231
1       a10  2018-01-07  100.0  4.283373  66.356134    5.492116
2       a11  2018-01-07   58.0  4.283373  71.549132  402.094327
3       a12  2018-01-07   64.0  4.283373  73.429514  211.692244
4       a13  2018-01-07  100.0  4.283373  63.923937    0.850536
5       a14  2018-01-07    NaN  4.283373        NaN         NaN
6       a15  2018-01-07    NaN  4.283373        NaN         NaN
7       a16  2018-01-07   56.0  4.283373  66.908970  529.843389
8        a2  2018-01-07   38.0  4.283373  76.063194  556.206108
9        a3  2018-01-07   50.0  4.283373  75.677199  508.592283

+ Print the last 10 rows of the data frame `df`:

In [ ]:
df.tail(10)

household        date  score      t_out     t_unit       hvac
5640       c41  2020-02-25   84.0  43.642388  70.929066  32.371903
5641       c42  2020-02-25   45.0  43.642388  76.235294   0.000000
5642       c43  2020-02-25   70.0  43.642388  78.302768  15.952602
5643       c44  2020-02-25   59.0  43.642388  76.494637  19.135139
5644       c45  2020-02-25   87.0  43.642388  71.165052  30.794281
5645       c46  2020-02-25    NaN  43.642388        NaN        NaN
5646       c47  2020-02-25   97.0  43.642388  68.603287   5.339391
5647       c48  2020-02-25   92.0  43.642388  73.429239  18.040078
5648       c49  2020-02-25    NaN  43.642388        NaN        NaN
5649       c50  2020-02-25   59.0  43.642388  77.716955  14.405155

+ Print summary statistics of the data set.

In [ ]:
df.describe()

score        t_out       t_unit         hvac
count  4887.000000  5650.000000  4887.000000  4887.000000
mean     74.372826    53.084123    74.172698    81.741860
std      21.643791    19.006199     2.608969    95.901059
min       0.000000     4.283373    63.923937     0.000000
25%      60.000000    37.522495    72.383504    18.321238
50%      79.000000    48.916667    74.178348    51.974687
75%      92.000000    73.079266    76.063591   110.487709
max     100.000000    82.819618    81.941295   693.526701

+ Notice that there is a column called "date", but pandas is not aware that this is actually a date.
Let's make it aware of that.

In [ ]:
df.date = pd.to_datetime(df['date'], format='%Y-%m-%d')

+ Count how many NaN values you have on each column.
*Hint: [Google it!](https://letmegooglethat.com/?q=pandas+count+NaN+values+per+column)

In [ ]:
df.isna().sum()

# For each coulmn count, specify the coulmn within df['']

# Alternatively, use len(df) - df.count()

household      0
date           0
score        763
t_out          0
t_unit       763
hvac         763
dtype: int64

+ Clean the data set by dropping all NaN values. Call the cleaned data `df_clean`.

In [ ]:
df_clean = df.dropna()
df_clean.head(10) #verifies that the NaN values are dropped. 

household       date  score     t_out     t_unit        hvac
0         a1 2018-01-07  100.0  4.283373  66.693229  246.473231
1        a10 2018-01-07  100.0  4.283373  66.356134    5.492116
2        a11 2018-01-07   58.0  4.283373  71.549132  402.094327
3        a12 2018-01-07   64.0  4.283373  73.429514  211.692244
4        a13 2018-01-07  100.0  4.283373  63.923937    0.850536
7        a16 2018-01-07   56.0  4.283373  66.908970  529.843389
8         a2 2018-01-07   38.0  4.283373  76.063194  556.206108
9         a3 2018-01-07   50.0  4.283373  75.677199  508.592283
10        a4 2018-01-07   99.0  4.283373  67.780613    0.000000
11        a5 2018-01-07   64.0  4.283373  74.854456  286.011150

+ Verify that there are no NaN values in `df_clean`.

In [ ]:
df_clean.head(10) #verifies that the NaN values are dropped. 
# Rows 5 and 6 had NaN values. 

+ How many unique households do we have and what are their unique names? 
+ Hint: [Google it!](https://letmegooglethat.com/?q=pandas+find+unique+values)

In [ ]:
uniqueHouseholds = df_clean.household.unique()
number_uniqueHouseholds = len(df_clean.household.unique()) 

print('There are', number_uniqueHouseholds, 'unique households and they are: ', uniqueHouseholds)


# df.household.value_counts() -> calculates the number of occurences of each unique value. 

There are 50 unique households and they are:  ['a1' 'a10' 'a11' 'a12' 'a13' 'a16' 'a2' 'a3' 'a4' 'a5' 'a6' 'a7' 'a8'
 'a9' 'b17' 'b18' 'b19' 'b20' 'b21' 'b22' 'b23' 'b24' 'b25' 'b26' 'b28'
 'b29' 'b30' 'b31' 'b33' 'c34' 'c35' 'c36' 'c37' 'c38' 'c39' 'c40' 'c41'
 'c42' 'c43' 'c44' 'c45' 'c46' 'c47' 'c48' 'c49' 'c50' 'a15' 'a14' 'b32'
 'b27']


+ Print summary statistics for your cleaned dataset.

In [ ]:
df_clean.describe()

score        t_out       t_unit         hvac
count  4887.000000  4887.000000  4887.000000  4887.000000
mean     74.372826    52.907260    74.172698    81.741860
std      21.643791    18.992310     2.608969    95.901059
min       0.000000     4.283373    63.923937     0.000000
25%      60.000000    37.522495    72.383504    18.321238
50%      79.000000    48.916667    74.178348    51.974687
75%      92.000000    73.079266    76.063591   110.487709
max     100.000000    82.819618    81.941295   693.526701

+ Save your cleaned dataset in a csv file using ``df_clean.to_csv``. Use the name ``temperature_clean.csv``.

In [ ]:
df_clean.to_csv('temperature_clean.csv')

+ Verify that the file exists by running the following lines of code (does not work on Windows):

In [ ]:
!ls -lth temperature_clean.csv

-rw------- 1 root root 353K Jul 11 15:15 temperature_clean.csv


In [ ]:
!head temperature_clean.csv

,household,date,score,t_out,t_unit,hvac
0,a1,2018-01-07,100.0,4.28337310850414,66.6932291666667,246.473230555556
1,a10,2018-01-07,100.0,4.28337310850414,66.3561342592595,5.49211611111111
2,a11,2018-01-07,58.0,4.28337310850414,71.5491319444439,402.094326666667
3,a12,2018-01-07,64.0,4.28337310850414,73.4295138888889,211.692243611111
4,a13,2018-01-07,100.0,4.28337310850414,63.9239365079362,0.850535833333333
7,a16,2018-01-07,56.0,4.28337310850414,66.9089699074074,529.843388611111
8,a2,2018-01-07,38.0,4.28337310850414,76.0631944444446,556.2061075
9,a3,2018-01-07,50.0,4.28337310850414,75.6771990740738,508.592283055556
10,a4,2018-01-07,99.0,4.28337310850414,67.7806134259262,0.0


+ Save the cleanded data set in an Microsoft Excel format. Look at [pandas.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) for the right function. Call the file ``temperature_clean.xlsx``.

In [ ]:
data = pd.DataFrame(df_clean)
data.to_excel('temperature_clean.xlsx')

+ Download the the newly created ``temperature_clean.xlsx`` file to your computer and open it up. There is no need to show something here. Just do it for your own education. If you are running the Jupyter notebook on your own computer, then there is nothing to do apart from finding the file. If you are working on Google Colab, see [this](https://stackoverflow.com/questions/48774285/how-to-download-file-created-in-colaboratory-workspace).

In [ ]:
%cd "/content/drive/My Drive/Colab Notebooks"
!pwd
!ls
from google.colab import files
files.download('temperature_clean.xlsx') #Successful Download! I had to play around this for a bit. 

/content/drive/My Drive/Colab Notebooks
/content/drive/My Drive/Colab Notebooks
'Copy of homework_01.ipynb'   temperature_clean.csv    temperature_raw.xlsx
'Copy of homework_02.ipynb'   temperature_clean.xlsx


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(lecture03:homework:problem2)=
## Problem 2 - Chemical reactions

In this problem, we are going to make a new DataFrame from a matrix of data.
We will use the catalysis dataset we introduced in the lecture.
As a reminder, this dataset is from a chemical reaction studied in {cite}`KATSOUNAROS2012270`.
The chemical reaction converts NO3 to N2. We have seven measurements at thirty second intervals. The masses are in grams. We saw in the lecture that the mass of the measured chemical species is not conserved, which suggests that there is at least one more thing we do not measure. The goal of this problem is to create a dataframe with the data and then add a column to it with our guess (prediction) for the mass of the unobserved chemical species.

+ First, let's make a list with the column names. The names are "Time, NO3, NO2, N2, NH3, N2O." Make the list and call it ``column_names``. Let me make part of the list and you complete the rest.

In [ ]:
column_names = ['Time', 'NO3', 'NO2', 'N2', 'NH3', 'N2)'] # Complete the rest of the list - Pay attention to
                               # the fact that the column names are strings.
column_names

['Time', 'NO3', 'NO2', 'N2', 'NH3', 'N2)']

+ Now, let's put the measured data in a numpy array. Remember that these are grams. The data are:

In [ ]:
# There is no point running this code block - I just wanted to put the raw data here
0,500.00,0.00,0.00,0.00,0.00
30,250.95,107.32,18.51,3.33,4.98
60,123.66,132.33,74.85,7.34,20.14
90,84.47,98.81,166.19,13.14,42.10
120,30.24,38.74,249.78,19.54,55.98
150,27.94,10.42,292.32,24.07,60.65
180,13.54,6.11,309.50,27.26,62.54

Let me make part of the matrix for you, and you should complete the rest:

In [ ]:
import numpy as np

raw_data = np.array(
    [
        [0,500.00,0.00,0.00,0.00,0.00],
        [30,250.95,107.32,18.51,3.33,4.98],
        [60,123.66,132.33,74.85,7.34,20.14],
        [90,84.47,98.81,166.19,13.14,42.10],
        [120,30.24,38.74,249.78,19.54,55.98], 
        [150,27.94,10.42,292.32,24.07,60.65], 
        [180,13.54,6.11,309.50,27.26,62.54]
    ]
)
raw_data

array([[  0.  , 500.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 30.  , 250.95, 107.32,  18.51,   3.33,   4.98],
       [ 60.  , 123.66, 132.33,  74.85,   7.34,  20.14],
       [ 90.  ,  84.47,  98.81, 166.19,  13.14,  42.1 ],
       [120.  ,  30.24,  38.74, 249.78,  19.54,  55.98],
       [150.  ,  27.94,  10.42, 292.32,  24.07,  60.65],
       [180.  ,  13.54,   6.11, 309.5 ,  27.26,  62.54]])

Remember that your matrix must have six columns and seven rows.

+ Let's put the data so far in a dataframe. 

In [ ]:
import pandas as pd

df = pd.DataFrame(data= raw_data, 
                  columns= column_names
                 )
df

Time     NO3     NO2      N2    NH3    N2)
0    0.0  500.00    0.00    0.00   0.00   0.00
1   30.0  250.95  107.32   18.51   3.33   4.98
2   60.0  123.66  132.33   74.85   7.34  20.14
3   90.0   84.47   98.81  166.19  13.14  42.10
4  120.0   30.24   38.74  249.78  19.54  55.98
5  150.0   27.94   10.42  292.32  24.07  60.65
6  180.0   13.54    6.11  309.50  27.26  62.54

+ In the lecture notes, we saw that the sum of the masses at each timestep was not conserved. Let's calculate how much mass is missing at each timestep. I will guide you through the steps. First, write some code to extract only the masses from the raw data.
Get all columns of ``raw_data`` except the first one:

In [ ]:
mass_data = raw_data[:, 1: ]
mass_data

array([[500.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [250.95, 107.32,  18.51,   3.33,   4.98],
       [123.66, 132.33,  74.85,   7.34,  20.14],
       [ 84.47,  98.81, 166.19,  13.14,  42.1 ],
       [ 30.24,  38.74, 249.78,  19.54,  55.98],
       [ 27.94,  10.42, 292.32,  24.07,  60.65],
       [ 13.54,   6.11, 309.5 ,  27.26,  62.54]])

+ Now, write code that sums all the columns for each row:

In [ ]:
total_measured_mass = mass_data.sum(axis = 1) # Sums all the columns for each row. #Choose axis = 1. 
total_measured_mass

array([500.  , 385.09, 358.32, 404.71, 394.28, 415.4 , 418.95])

+ Now, find how much is the missing mass of the unobserved chemical species X by subtracting the total measured mass from the initial mass (which was 500 grams).

In [ ]:
initialMass = 500

mass_of_X = initialMass - total_measured_mass
mass_of_X

array([  0.  , 114.91, 141.68,  95.29, 105.72,  84.6 ,  81.05])

Very nice! You just made your first model! Your model is:
$$
\text{mass of X} = 500\;\text{grams} - \text{mass of NO3} - \dots -\text{mass of N2O}.
$$
Notice that we did not use just data to build this model.
We used a physical principle (conservation of mass) plus data!
It is a special kind of model.
We will learn more about models in later lectures!

+ Let's now make a new dataframe that also contains X. We need to add a column to our original dataframe. This is super simple. You can do it like this:

In [ ]:
df['X'] = mass_of_X
df

Time     NO3     NO2      N2    NH3    N2)       X
0    0.0  500.00    0.00    0.00   0.00   0.00    0.00
1   30.0  250.95  107.32   18.51   3.33   4.98  114.91
2   60.0  123.66  132.33   74.85   7.34  20.14  141.68
3   90.0   84.47   98.81  166.19  13.14  42.10   95.29
4  120.0   30.24   38.74  249.78  19.54  55.98  105.72
5  150.0   27.94   10.42  292.32  24.07  60.65   84.60
6  180.0   13.54    6.11  309.50  27.26  62.54   81.05

+ Now, save the dataframe to an Excel file.

In [ ]:
data = pd.DataFrame(df)
data.to_excel('chemicalReaction.xlsx')